#!/usr/bin/env python3
"""Regenerate docs/stylesheets/extra.css from docs/theme/tokens.json.

Edit the JSON, then run this script. ``--check`` fails when the stylesheet
is stale. ``--from`` reads a read-only graph-ted checkout (frontend/) and
fills only tokens it can name. It does not invent missing values.

See docs/theme/README.md.
"""

from __future__ import annotations

import argparse
import base64
import json
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_TOKENS = ROOT / "docs" / "theme" / "tokens.json"
DEFAULT_CSS = ROOT / "docs" / "stylesheets" / "extra.css"

_LENGTH = re.compile(r"^\d+(?:\.\d+)?(?:px|rem|em)$")
_HEX = re.compile(r"^#(?:[0-9A-Fa-f]{3}|[0-9A-Fa-f]{6}|[0-9A-Fa-f]{8})$")
_SKIP_DIRS = {
    "node_modules",
    "dist",
    "build",
    ".git",
    "coverage",
    ".next",
    ".turbo",
}
_SOURCE_SUFFIXES = {".css", ".scss", ".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".json"}

_ICON_PACKAGES = {
    "lucide-react": "lucide",
    "lucide": "lucide",
    "@lucide/react": "lucide",
    "react-icons": "react-icons",
    "@chakra-ui/icons": "chakra-icons",
    "@heroicons/react": "heroicons",
    "phosphor-react": "phosphor",
    "@phosphor-icons/react": "phosphor",
    "@mui/icons-material": "material-icons",
}
_UI_PACKAGES = (
    "@chakra-ui/react",
    "@mui/material",
    "@radix-ui/themes",
    "antd",
)

_DARK_SEGMENTS = {"dark", "slate", "night", "darkmode"}
_LIGHT_SEGMENTS = {"light", "default", "day", "lightmode"}
_COLOR_LEAVES = {
    "header": "header",
    "headerbg": "header",
    "headerbackground": "header",
    "navbar": "header",
    "navbarbg": "header",
    "navbarbackground": "header",
    "appbar": "header",
    "appbarbg": "header",
    "headertext": "header_text",
    "navbartext": "header_text",
    "onheader": "header_text",
    "headerfg": "header_text",
    "link": "link",
    "links": "link",
    "linkcolor": "link",
    "brand": "brand",
    "brandteal": "brand",
    "accent": "accent",
    "focus": "focus",
    "focusring": "focus",
    "ring": "focus",
}
_LAYOUT_LEAVES = {
    "navbarheight": "navbar_height",
    "headerheight": "navbar_height",
    "navheight": "navbar_height",
    "appbarheight": "navbar_height",
    "logoheight": "logo_height",
    "markheight": "logo_height",
    "marksize": "logo_height",
}
_RADIUS_PARENTS = {"radius", "radii", "rounded"}
_SHADOW_PARENTS = {"shadow", "shadows"}
_SPACE_PARENTS = {"space", "spacing", "sizes"}
_FONT_PARENTS = {"font", "fonts", "fontfamily"}
_FONT_LEAVES = {
    "body": "text",
    "text": "text",
    "sans": "text",
    "heading": "text",
    "mono": "code",
    "code": "code",
    "codefont": "code",
}

_FONT_FACE = """\
/* Generated from docs/theme/tokens.json by scripts/sync_tokens.py.
   Do not edit this file by hand. Regenerate with:
   python scripts/sync_tokens.py
   Brand #009999 is the wordmark, large surfaces, and dark-scheme links
   (4.61:1 on slate). It is 3.49:1 on white, so light-scheme text uses
   interactive #007A7A (5.17:1 with white). The header is the app navbar:
   Chakra bg.muted with fg text and a 1px border, not the interactive teal. */

/* Docs text is Inter (variable, roman + italic). Code is JetBrains Mono
   at weights 400 and 700, with italics. Both are OFL and live in
   ../assets/fonts/ with their license texts. theme.font is false, so
   these variables replace the Google Fonts block. */
@font-face {
  font-family: "Inter";
  font-style: normal;
  font-weight: 100 900;
  font-display: swap;
  src: url("../assets/fonts/InterVariable.woff2") format("woff2");
}

@font-face {
  font-family: "Inter";
  font-style: italic;
  font-weight: 100 900;
  font-display: swap;
  src: url("../assets/fonts/InterVariable-Italic.woff2") format("woff2");
}

@font-face {
  font-family: "JetBrains Mono";
  font-style: normal;
  font-weight: 400;
  font-display: swap;
  src: url("../assets/fonts/JetBrainsMono-Regular.woff2") format("woff2");
}

@font-face {
  font-family: "JetBrains Mono";
  font-style: italic;
  font-weight: 400;
  font-display: swap;
  src: url("../assets/fonts/JetBrainsMono-Italic.woff2") format("woff2");
}

@font-face {
  font-family: "JetBrains Mono";
  font-style: normal;
  font-weight: 700;
  font-display: swap;
  src: url("../assets/fonts/JetBrainsMono-Bold.woff2") format("woff2");
}

@font-face {
  font-family: "JetBrains Mono";
  font-style: italic;
  font-weight: 700;
  font-display: swap;
  src: url("../assets/fonts/JetBrainsMono-BoldItalic.woff2") format("woff2");
}
"""


# Permalink icon: Material Design Icons "link" (24px), the same path Material
# for MkDocs bundles as material/link. It is embedded as a base64 data URI so
# the docs load nothing remote and the stylesheet carries no URL text.
_LINK_ICON_SVG = (
    '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24"><path d="'
    "M3.9 12c0-1.71 1.39-3.1 3.1-3.1h4V7H7a5 5 0 0 0-5 5 5 5 0 0 0 5 5h4v-1.9H7"
    "c-1.71 0-3.1-1.39-3.1-3.1M8 13h8v-2H8zm9-6h-4v1.9h4c1.71 0 3.1 1.39 3.1 3.1"
    's-1.39 3.1-3.1 3.1h-4V17h4a5 5 0 0 0 5-5 5 5 0 0 0-5-5"/></svg>'
)


def link_icon_data_uri() -> str:
    encoded = base64.b64encode(_LINK_ICON_SVG.encode("utf-8")).decode("ascii")
    return f"data:image/svg+xml;base64,{encoded}"


def norm_key(value: str) -> str:
    return re.sub(r"[^a-z0-9]", "", value.lower())


def load_tokens(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def dump_tokens(tokens: dict) -> str:
    return json.dumps(tokens, indent=2, ensure_ascii=False) + "\n"


def _css_string(value: str) -> str:
    value = value.strip()
    inner = value
    if (
        len(value) >= 2
        and value[0] == value[-1]
        and value[0] in "\"'"
        and value.count(value[0]) == 2
    ):
        inner = value[1:-1]
    if re.fullmatch(r"[A-Za-z0-9 ]+", inner):
        return f'"{inner}"'
    # A font stack such as '"Inter Variable", Inter, sans-serif' stays as written.
    return value


def _px(value: str, root: str | None) -> str:
    """Turn app ``rem`` into px at the app's root size.

    Material sets ``html { font-size: 125% }``, so an app ``0.25rem`` would
    render 25% larger in the docs. Without a known root size, keep ``rem``.
    """
    match = re.fullmatch(r"(\d+(?:\.\d+)?)rem", str(value).strip())
    base = re.fullmatch(r"(\d+(?:\.\d+)?)px", str(root or "").strip())
    if not match or not base:
        return value
    px = float(match.group(1)) * float(base.group(1))
    return f"{px:g}px"


def _var_key(value: str) -> str:
    """CSS custom-property suffix: ``0.5`` -> ``0-5``, ``2xl`` -> ``2xl``."""
    return re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")


def _scheme_block(
    scheme: str,
    colors: dict,
    *,
    dark_buttons: dict | None,
    interactive: str,
    on_interactive: str,
) -> str:
    header = colors["header"]
    header_text = colors["header_text"]
    header_border = colors.get("header_border", "transparent")
    header_muted = colors.get("header_muted", header_text)
    link = colors["link"]
    accent = colors.get("accent", link)
    # Primary stays the interactive teal so buttons and the footer do not
    # pick up the neutral navbar. The navbar uses --gt-header-*.
    fill = colors.get("button_fill", interactive)
    label = colors.get("button_text", on_interactive)
    lines = [
        f'[data-md-color-scheme="{scheme}"] {{',
        f"  --md-primary-fg-color: {fill};",
        f"  --md-primary-fg-color--light: {colors.get('brand', fill)};",
        f"  --md-primary-fg-color--dark: {fill};",
        f"  --md-primary-bg-color: {label};",
        f"  --md-primary-bg-color--light: {label}b3;",
        f"  --md-accent-fg-color: {accent};",
        f"  --md-accent-fg-color--transparent: {accent}1a;",
        f"  --md-accent-bg-color: {label};",
        f"  --md-accent-bg-color--light: {label}b3;",
        f"  --md-typeset-a-color: {link};",
        f"  --md-footer-bg-color: {interactive};",
        f"  --md-footer-bg-color--dark: {interactive};",
        f"  --md-footer-fg-color: {on_interactive};",
        f"  --md-footer-fg-color--light: {on_interactive}b3;",
        f"  --md-footer-fg-color--lighter: {on_interactive}73;",
        f"  --gt-header-bg: {header};",
        f"  --gt-header-fg: {header_text};",
        f"  --gt-header-border: {header_border};",
        f"  --gt-header-muted: {header_muted};",
        "}",
        "",
        f'[data-md-color-scheme="{scheme}"] .md-typeset .admonition.note,',
        f'[data-md-color-scheme="{scheme}"] .md-typeset details.note,',
        f'[data-md-color-scheme="{scheme}"] .md-typeset .admonition.info,',
        f'[data-md-color-scheme="{scheme}"] .md-typeset details.info {{',
        f"  border-color: {link};",
        "}",
        "",
        f'[data-md-color-scheme="{scheme}"] .md-typeset .admonition.note:focus-within,',
        f'[data-md-color-scheme="{scheme}"] .md-typeset details.note:focus-within,',
        f'[data-md-color-scheme="{scheme}"] .md-typeset .admonition.info:focus-within,',
        f'[data-md-color-scheme="{scheme}"] .md-typeset details.info:focus-within {{',
        f"  box-shadow: 0 0 0 0.2rem {link}1a;",
        "}",
        "",
        f'[data-md-color-scheme="{scheme}"] .md-typeset .note > .admonition-title,',
        f'[data-md-color-scheme="{scheme}"] .md-typeset .note > summary,',
        f'[data-md-color-scheme="{scheme}"] .md-typeset .info > .admonition-title,',
        f'[data-md-color-scheme="{scheme}"] .md-typeset .info > summary {{',
        f"  background-color: {link}1a;",
        "}",
        "",
        f'[data-md-color-scheme="{scheme}"] .md-typeset .note > .admonition-title::before,',
        f'[data-md-color-scheme="{scheme}"] .md-typeset .note > summary::before,',
        f'[data-md-color-scheme="{scheme}"] .md-typeset .info > .admonition-title::before,',
        f'[data-md-color-scheme="{scheme}"] .md-typeset .info > summary::before {{',
        f"  background-color: {link};",
        "}",
        "",
        f'[data-md-color-scheme="{scheme}"] .md-typeset table:not([class]) th {{',
        f"  color: {link};",
        f"  border-bottom-color: {link};",
        "}",
        "",
    ]
    if dark_buttons:
        fill = dark_buttons.get("button_fill", interactive)
        label = dark_buttons.get("button_text", on_interactive)
        lines.extend(
            [
                f'[data-md-color-scheme="{scheme}"] .md-typeset .md-button {{',
                f"  color: {link};",
                f"  border-color: {link};",
                "}",
                "",
                f'[data-md-color-scheme="{scheme}"] .md-typeset .md-button--primary {{',
                f"  background-color: {fill};",
                f"  border-color: {fill};",
                f"  color: {label};",
                "}",
                "",
                f'[data-md-color-scheme="{scheme}"] .md-typeset .md-button:focus,',
                f'[data-md-color-scheme="{scheme}"] .md-typeset .md-button:hover {{',
                f"  background-color: {fill};",
                f"  border-color: {fill};",
                f"  color: {label};",
                "}",
                "",
            ]
        )
    return "\n".join(lines)


def _optional_groups(tokens: dict) -> str:
    chunks: list[str] = []
    root = (tokens.get("layout") or {}).get("root_font_size")
    radius = tokens.get("radius")
    if isinstance(radius, dict) and radius:
        radius = {key: _px(value, root) for key, value in radius.items()}
        panel = next(
            (radius[key] for key in ("md", "l3", "default", "base", "sm") if key in radius), None
        )
        # Chakra buttons and inputs use the l2 control radius; panels use md.
        control = next((radius[key] for key in ("l2", "sm") if key in radius), panel)
        lines = [":root {"]
        for key, value in radius.items():
            lines.append(f"  --gt-radius-{_var_key(key)}: {value};")
        lines.append("}")
        if control:
            lines.extend(
                [
                    "",
                    ".md-typeset .md-button,",
                    ".md-search__form,",
                    ".md-search__input {",
                    f"  border-radius: {control};",
                    "}",
                ]
            )
        if panel:
            lines.extend(
                [
                    "",
                    ".md-typeset pre,",
                    ".md-typeset pre > code,",
                    ".md-typeset .admonition,",
                    ".md-typeset details {",
                    f"  border-radius: {panel};",
                    "}",
                ]
            )
        chunks.append("\n".join(lines))
    spacing = tokens.get("spacing")
    if isinstance(spacing, dict) and spacing:
        lines = [":root {"]
        for key, value in spacing.items():
            lines.append(f"  --gt-space-{_var_key(key)}: {_px(value, root)};")
        lines.append("}")
        chunks.append("\n".join(lines))
    shadow = tokens.get("shadow")
    if isinstance(shadow, dict) and shadow:
        flat = {key: value for key, value in shadow.items() if isinstance(value, str)}
        lines = []
        if flat:
            lines.append(":root {")
            for key, value in flat.items():
                lines.append(f"  --gt-shadow-{_var_key(key)}: {value};")
            lines.append("}")
        # Chakra semantic shadows carry a light and a dark value.
        for scheme, mode in (("default", "light"), ("slate", "dark")):
            scoped = {
                key: value[mode]
                for key, value in shadow.items()
                if isinstance(value, dict) and mode in value
            }
            if scoped:
                if lines:
                    lines.append("")
                lines.append(f'[data-md-color-scheme="{scheme}"] {{')
                for key, value in scoped.items():
                    lines.append(f"  --gt-shadow-{_var_key(key)}: {value};")
                lines.append("}")
        card_key = next((key for key in ("card", "md", "default") if key in shadow), None)
        card = None
        if card_key:
            card = (
                shadow[card_key]
                if isinstance(shadow[card_key], str)
                else f"var(--gt-shadow-{_var_key(card_key)})"
            )
        if card:
            lines.extend(
                [
                    "",
                    ".md-typeset .admonition,",
                    ".md-typeset details {",
                    f"  box-shadow: {card};",
                    "}",
                ]
            )
        chunks.append("\n".join(lines))
    button = tokens.get("button")
    if isinstance(button, dict) and button:
        lines = [
            "/* App buttons: Chakra button recipe, default size. */",
            ".md-typeset .md-button {",
            "  display: inline-flex;",
            "  align-items: center;",
            "  justify-content: center;",
        ]
        if button.get("height"):
            lines.append(f"  min-height: {_px(button['height'], root)};")
        if button.get("padding_x"):
            lines.append(f"  padding: 0 {_px(button['padding_x'], root)};")
        if button.get("font_size"):
            lines.append(f"  font-size: {_px(button['font_size'], root)};")
        if button.get("line_height"):
            lines.append(f"  line-height: {_px(button['line_height'], root)};")
        lines.append("}")
        chunks.append("\n".join(lines))
    if not chunks:
        return ""
    return "\n\n".join(chunks) + "\n"


def render_css(tokens: dict) -> str:
    light = tokens["color"]["light"]
    dark = tokens["color"]["dark"]
    font = tokens["font"]
    layout = tokens["layout"]
    focus = tokens["focus"]
    navbar = layout["navbar_height"]
    logo = layout["logo_height"]
    brand = tokens["color"]["brand"]
    interactive = tokens["color"].get("interactive", "#007A7A")
    on_interactive = tokens["color"].get("on_interactive", "#FFFFFF")
    text_font = _css_string(font["text"])
    icon = link_icon_data_uri()
    code_font = _css_string(font["code"])
    body = f"""\
:root {{
  --md-text-font: {text_font};
  --md-code-font: {code_font};
}}

{_scheme_block("default", light, dark_buttons=None, interactive=interactive, on_interactive=on_interactive)}
{_scheme_block("slate", dark, dark_buttons=dark, interactive=interactive, on_interactive=on_interactive)}
/* Header row matches the app navbar: {navbar} tall including the 1px
   border, mark {logo}. Flex centering leaves the app's 4px inset.
   The logo file is unchanged. */
.md-header,
.md-tabs {{
  background-color: var(--gt-header-bg);
  color: var(--gt-header-fg);
  box-shadow: none;
}}

.md-header--shadow {{
  box-shadow: none;
}}

.md-header {{
  height: {navbar};
  box-sizing: border-box;
  border-bottom: 1px solid var(--gt-header-border);
}}

.md-tabs {{
  border-bottom: 1px solid var(--gt-header-border);
}}

/* One border, under the tab row when tabs are on screen. The header
   keeps a 1px edge so the logo row stays {navbar}. */
@media screen and (min-width: 76.25em) {{
  .md-header {{
    border-bottom-color: var(--gt-header-bg);
  }}
}}

.md-header__inner {{
  height: calc({navbar} - 1px);
  min-height: calc({navbar} - 1px);
}}

.md-header__title {{
  height: calc({navbar} - 1px);
  line-height: calc({navbar} - 1px);
}}

.md-header__button.md-logo {{
  display: inline-block;
  margin-top: 0;
  margin-bottom: 0;
  padding: 0;
}}

@media screen and (max-width: 76.234375em) {{
  .md-header__button.md-logo {{
    display: inline-block;
  }}
}}

.md-header__button.md-logo img,
.md-header__button.md-logo svg {{
  height: {logo};
  width: auto;
}}

/* Focus on the neutral bar uses the scheme focus color. */
[data-md-color-scheme="default"] .md-header__button,
[data-md-color-scheme="default"] .md-tabs__link,
[data-md-color-scheme="default"] .md-source {{
  outline-color: {focus["light"]};
}}

[data-md-color-scheme="slate"] .md-header__button,
[data-md-color-scheme="slate"] .md-tabs__link,
[data-md-color-scheme="slate"] .md-source {{
  outline-color: {focus["dark"]};
}}

/* Search sits on gray, so the field uses the navbar border and fg.
   The open overlay keeps Material's page colors. */
@media screen and (min-width: 60em) {{
  .md-header .md-search__form,
  .md-header .md-search__form:hover {{
    background-color: var(--gt-header-border);
    color: var(--gt-header-fg);
  }}

  .md-header .md-search__input {{
    color: var(--gt-header-fg);
  }}

  .md-header .md-search__input::placeholder,
  .md-header .md-search__input + .md-search__icon {{
    color: var(--gt-header-muted);
  }}
}}

.md-typeset :focus-visible {{
  outline-color: var(--md-accent-fg-color);
}}

/* Brand teal as a border on code, not as text. */
.md-typeset pre > code {{
  border-left: 3px solid {brand};
}}

.md-clipboard {{
  color: var(--md-typeset-a-color);
}}

/* Permalinks: a small link icon in the link color, hidden until the
   heading is hovered or the link has keyboard focus. The pilcrow stays in
   the HTML as the link text (anchors and markup are unchanged); it is
   moved out of the box and the icon is drawn over it. Screen only, so
   Material's print rule still drops permalinks. */
@media screen {{
  .md-typeset .headerlink {{
    --gt-permalink-icon: url("{icon}");
    position: relative;
    display: inline-block;
    width: 0.75em;
    height: 0.75em;
    margin-left: 0.35em;
    overflow: hidden;
    white-space: nowrap;
    text-indent: 100%;
    vertical-align: -0.05em;
    color: var(--md-typeset-a-color);
    opacity: 0;
  }}

  .md-typeset .headerlink::before {{
    content: "";
    position: absolute;
    inset: 0;
    background-color: currentColor;
    -webkit-mask: var(--gt-permalink-icon) center / contain no-repeat;
    mask: var(--gt-permalink-icon) center / contain no-repeat;
  }}

  .md-typeset :hover > .headerlink,
  .md-typeset :focus-within > .headerlink,
  .md-typeset .headerlink:focus-visible {{
    opacity: 1;
  }}

  .md-typeset .headerlink:hover,
  .md-typeset .headerlink:focus-visible {{
    color: var(--md-typeset-a-color);
  }}
}}

/* Light-scheme primary buttons stay white on the interactive teal.
   A slight mix with black shows hover without a second brand color. */
[data-md-color-scheme="default"] .md-typeset .md-button--primary:focus,
[data-md-color-scheme="default"] .md-typeset .md-button--primary:hover {{
  background-color: color-mix(in srgb, var(--md-primary-fg-color) 85%, #000);
  border-color: color-mix(in srgb, var(--md-primary-fg-color) 85%, #000);
  color: {on_interactive};
}}

.md-typeset .gt-hero {{
  display: block;
  width: 340px;
  max-width: 100%;
  height: auto;
  margin: 0.25rem auto 1.25rem;
}}
"""
    optional = _optional_groups(tokens)
    if optional:
        body = body.rstrip() + "\n\n" + optional
    return _FONT_FACE + "\n" + body.rstrip() + "\n"


def css_matches(tokens: dict, css_text: str) -> bool:
    return render_css(tokens) == css_text


def _unquote(value: str) -> str:
    value = value.strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        return value[1:-1]
    return value


def _scan_literals(text: str) -> list[tuple[tuple[str, ...], str]]:
    """Pull key/value literals and remember the brace path around each one."""
    pattern = re.compile(
        r"""
        (?P<key>[A-Za-z_][\w-]*|"[\w.-]+"|'[\w.-]+'|\d+(?:\.\d+)?)\s*:\s*(?P<open>\{)
        | (?P<key2>[A-Za-z_][\w-]*|"[\w.-]+"|'[\w.-]+'|\d+(?:\.\d+)?)\s*:\s*(?P<val>"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|\#[0-9A-Fa-f]{3,8}|\d+(?:\.\d+)?(?:px|rem|em))
        | (?P<css>--(?P<csskey>[\w-]+)\s*:\s*(?P<cssval>[^;]+);)
        | (?P<close>\})
        """,
        re.VERBOSE,
    )
    found: list[tuple[tuple[str, ...], str]] = []
    stack: list[str] = []
    for match in pattern.finditer(text):
        if match.group("open"):
            stack.append(_unquote(match.group("key")))
            continue
        if match.group("close"):
            if stack:
                stack.pop()
            continue
        if match.group("css"):
            found.append((("--" + match.group("csskey"),), match.group("cssval").strip()))
            continue
        key = _unquote(match.group("key2"))
        found.append((_chakra_path(tuple(stack + [key])), _unquote(match.group("val"))))
    return found


def _chakra_path(path: tuple[str, ...]) -> tuple[str, ...]:
    """Fold Chakra v3 token shapes onto the token name.

    ``brand: { value: X }`` becomes ``brand``. ``fg: { value: { _dark: X } }``
    becomes ``_dark / fg`` so the scheme rules below see it.
    """
    if len(path) >= 2 and path[-1] == "value":
        return path[:-1]
    if len(path) >= 3 and path[-2] == "value" and path[-1] in {"_light", "_dark"}:
        return path[:-3] + (path[-1], path[-3])
    return path


def _scheme_for(path: tuple[str, ...]) -> str | None:
    names = {norm_key(part) for part in path[:-1]}
    dark = bool(names & _DARK_SEGMENTS)
    light = bool(names & _LIGHT_SEGMENTS)
    if dark and not light:
        return "dark"
    if light and not dark:
        return "light"
    return None


def _parents(path: tuple[str, ...]) -> set[str]:
    return {norm_key(part) for part in path[:-1]}


_CHAKRA_THEME = Path("node_modules/@chakra-ui/react/dist/esm/theme")
_CHAKRA_REF = re.compile(r"\{([\w.]+?)(?:/(\d+))?\}")


def _chakra_tokens(theme: Path, rel: str) -> list[tuple[tuple[str, ...], str]]:
    path = theme / rel
    if not path.is_file():
        return []
    return _scan_literals(path.read_text(encoding="utf-8"))


def _chakra_resolve(value: str, table: dict[str, str]) -> str:
    """Resolve ``{radii.sm}`` and ``{colors.gray.900/10}`` the way Chakra emits them."""

    def sub(match: re.Match) -> str:
        name, alpha = match.group(1), match.group(2)
        resolved = table.get(name, name)
        if alpha:
            return f"color-mix(in srgb, {resolved} {alpha}%, transparent)"
        return resolved

    return _CHAKRA_REF.sub(sub, value)


def chakra_defaults(frontend: Path) -> dict:
    """Radii, spacing, and shadows from the Chakra package the app installs.

    Used only when the app theme extends Chakra's ``defaultConfig``. The
    values are read from ``frontend/node_modules``; nothing is hard-coded.
    """
    theme = frontend / _CHAKRA_THEME
    if not theme.is_dir():
        return {}
    version = None
    package = frontend / "node_modules" / "@chakra-ui" / "react" / "package.json"
    if package.is_file():
        version = json.loads(package.read_text(encoding="utf-8")).get("version")
    table: dict[str, str] = {}
    for key_path, value in _chakra_tokens(theme, "tokens/colors.js"):
        table["colors." + ".".join(key_path)] = value
    radius: dict[str, str] = {}
    for key_path, value in _chakra_tokens(theme, "tokens/radius.js"):
        radius[key_path[-1]] = value
        table["radii." + key_path[-1]] = value
    for key_path, value in _chakra_tokens(theme, "semantic-tokens/radii.js"):
        radius[key_path[-1]] = _chakra_resolve(value, table)
    spacing = {
        key_path[-1]: value for key_path, value in _chakra_tokens(theme, "tokens/spacing.js")
    }
    shadow: dict[str, dict[str, str]] = {}
    for key_path, value in _chakra_tokens(theme, "semantic-tokens/shadows.js"):
        if len(key_path) >= 2 and key_path[-2] in {"_light", "_dark"}:
            scheme = "light" if key_path[-2] == "_light" else "dark"
            shadow.setdefault(key_path[-1], {})[scheme] = _chakra_resolve(value, table)
    font_sizes = {
        key_path[-1]: value for key_path, value in _chakra_tokens(theme, "tokens/font-sizes.js")
    }
    text_styles: dict[str, dict[str, str]] = {}
    for key_path, value in _chakra_tokens(theme, "text-styles.js"):
        if len(key_path) == 3 and key_path[1] == "value":
            text_styles.setdefault(key_path[0], {})[key_path[2]] = value
    recipe = _chakra_tokens(theme, "recipes/button.js")
    default_size = next(
        (value for key_path, value in recipe if key_path[-2:] == ("defaultVariants", "size")), None
    )
    button: dict[str, str] = {}
    if default_size:
        size = {
            key_path[-1]: value
            for key_path, value in recipe
            if key_path[:-1] == ("variants", "size", default_size)
        }
        if size.get("h") in spacing:
            button["height"] = spacing[size["h"]]
        if size.get("px") in spacing:
            button["padding_x"] = spacing[size["px"]]
        style = text_styles.get(size.get("textStyle", ""), {})
        if style.get("fontSize") in font_sizes:
            button["font_size"] = font_sizes[style["fontSize"]]
        if style.get("lineHeight"):
            button["line_height"] = style["lineHeight"]
        if button:
            button["size"] = default_size
    return {
        "radius": radius,
        "spacing": spacing,
        "shadow": shadow,
        "button": button,
        "version": version,
    }


def _app_git_ref(checkout: Path) -> str | None:
    try:
        result = subprocess.run(
            ["git", "-C", str(checkout), "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            check=False,
        )
    except OSError:
        return None
    ref = result.stdout.strip()
    return ref if result.returncode == 0 and re.fullmatch(r"[0-9a-f]{4,40}", ref) else None


def _icon_families(frontend: Path, sources: list[str]) -> list[str]:
    """react-icons sub-packages imported by the app, most used first."""
    counts: dict[str, int] = {}
    for text in sources:
        for family in re.findall(r"from\s+[\"']react-icons/([a-z0-9]+)[\"']", text):
            if family != "lib":
                counts[family] = counts.get(family, 0) + 1
    return sorted(counts, key=lambda name: (-counts[name], name))


def extract_mappings(frontend: Path) -> dict:
    """Return token fields found under frontend/. Empty when nothing maps."""
    package_path = frontend / "package.json"
    if not package_path.is_file():
        raise FileNotFoundError(f"missing {package_path}")
    package = json.loads(package_path.read_text(encoding="utf-8"))
    deps: dict[str, str] = {}
    for section in ("dependencies", "devDependencies", "peerDependencies"):
        block = package.get(section) or {}
        if isinstance(block, dict):
            deps.update({str(key): str(value) for key, value in block.items()})
    icon_packages = [name for name in deps if name in _ICON_PACKAGES]
    ui_packages = [name for name in _UI_PACKAGES if name in deps]
    icon_set = _ICON_PACKAGES[icon_packages[0]] if icon_packages else None

    colors = {"light": {}, "dark": {}, "brand": None}
    layout: dict[str, str] = {}
    radius: dict[str, str] = {}
    spacing: dict[str, str] = {}
    shadow: dict[str, str] = {}
    font: dict[str, str] = {}
    focus: dict[str, str] = {}
    sources: list[str] = []

    for path in frontend.rglob("*"):
        if not path.is_file():
            continue
        if any(part in _SKIP_DIRS for part in path.parts):
            continue
        if path.name in {"package.json", "package-lock.json", "yarn.lock", "pnpm-lock.yaml"}:
            continue
        if path.suffix.lower() not in _SOURCE_SUFFIXES:
            continue
        if path.stat().st_size > 200_000:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        sources.append(text)
        for key_path, raw in _scan_literals(text):
            if not key_path:
                continue
            leaf = norm_key(key_path[-1].lstrip("-"))
            value = raw.strip().strip("\"'")
            parents = _parents(key_path)
            if leaf in _LAYOUT_LEAVES and _LENGTH.match(value):
                layout[_LAYOUT_LEAVES[leaf]] = value
                continue
            if leaf == "fontsize" and key_path[-2:-1] == ("html",) and value.endswith("px"):
                layout["root_font_size"] = value
                continue
            if leaf in _COLOR_LEAVES and (_HEX.match(value) or value.startswith("#")):
                field = _COLOR_LEAVES[leaf]
                scheme = _scheme_for(key_path)
                if field == "brand" and scheme is None:
                    colors["brand"] = value
                    colors["light"]["brand"] = value
                    colors["dark"]["brand"] = value
                elif field == "focus" and scheme is None:
                    focus["ring"] = value
                elif scheme and field == "focus":
                    focus[scheme] = value
                    colors[scheme]["focus"] = value
                elif scheme:
                    colors[scheme][field] = value
                continue
            if parents & _RADIUS_PARENTS and _LENGTH.match(value):
                radius[key_path[-1]] = value
                continue
            if parents & _SHADOW_PARENTS and value:
                shadow[key_path[-1]] = value
                continue
            if parents & _SPACE_PARENTS and _LENGTH.match(value):
                spacing[key_path[-1]] = value
                continue
            if parents & _FONT_PARENTS and leaf in _FONT_LEAVES and value:
                font[_FONT_LEAVES[leaf]] = raw.strip()

    chakra_base = {}
    if "@chakra-ui/react" in deps and any("defaultConfig" in text for text in sources):
        chakra_base = chakra_defaults(frontend)
        # App overrides win over the Chakra defaults they extend.
        radius = {**chakra_base.get("radius", {}), **radius}
        spacing = {**chakra_base.get("spacing", {}), **spacing}
        shadow = {**chakra_base.get("shadow", {}), **shadow}
    icon_families = _icon_families(frontend, sources) if icon_set == "react-icons" else []

    mapped = bool(
        colors["light"]
        or colors["dark"]
        or colors["brand"]
        or layout
        or radius
        or spacing
        or shadow
        or font
        or focus
        or icon_set
    )
    return {
        "mapped": mapped,
        "icon_packages": icon_packages,
        "ui_packages": ui_packages,
        "icon_set": icon_set,
        "icon_families": icon_families,
        "chakra_defaults": bool(chakra_base),
        "chakra_version": chakra_base.get("version"),
        "button": chakra_base.get("button", {}),
        "colors": colors,
        "layout": layout,
        "radius": radius,
        "spacing": spacing,
        "shadow": shadow,
        "font": font,
        "focus": focus,
    }


def enforce_contrast(tokens: dict) -> list[str]:
    """Apply the documented WCAG AA exceptions. Returns notes for provenance."""
    notes: list[str] = []
    light = tokens["color"]["light"]
    dark = tokens["color"]["dark"]
    interactive = tokens["color"].get("interactive", "#007A7A")
    on_interactive = tokens["color"].get("on_interactive", "#FFFFFF")
    dark_link = tokens["color"].get("dark_link", "#009999")
    if str(light.get("link", "")).lower() == "#009999":
        light["link"] = interactive
        light["accent"] = interactive
        notes.append("light link #009999 fails AA on white; stylesheet uses interactive #007A7A.")
    if str(light.get("header", "")).lower() == "#009999":
        light["header"] = interactive
        light["header_text"] = on_interactive
        notes.append("light header #009999 fails AA with white text; stylesheet uses #007A7A.")
    # #009999 on slate is 4.61:1 and matches the app, so it is kept.
    # #007A7A on slate is 3.12:1.
    if str(dark.get("link", "")).lower() == "#007a7a":
        dark["link"] = dark_link
        dark["accent"] = dark_link
        if str(dark.get("focus", "")).lower() == "#007a7a":
            dark["focus"] = dark_link
        focus = tokens.get("focus")
        if isinstance(focus, dict) and str(focus.get("dark", "")).lower() == "#007a7a":
            focus["dark"] = dark_link
        notes.append("dark link #007A7A is 3.12:1 on slate; stylesheet uses #009999.")
    if str(dark.get("header", "")).lower() == "#009999":
        dark["header"] = interactive
        dark["header_text"] = on_interactive
        notes.append("dark header #009999 fails AA with white text; stylesheet uses #007A7A.")
    return notes


def apply_extraction(tokens: dict, found: dict, git_ref: str | None = None) -> dict:
    updated = json.loads(json.dumps(tokens))
    colors = found["colors"]
    if colors.get("brand"):
        updated["color"]["brand"] = colors["brand"]
    for scheme in ("light", "dark"):
        for key, value in colors[scheme].items():
            updated["color"][scheme][key] = value
    for key, value in found["layout"].items():
        updated["layout"][key] = value
    if found["radius"]:
        updated["radius"] = found["radius"]
    if found["spacing"]:
        updated["spacing"] = found["spacing"]
    if found["shadow"]:
        updated["shadow"] = found["shadow"]
    for key, value in found["font"].items():
        updated["font"][key] = value
    focus = found["focus"]
    if "light" in focus:
        updated["focus"]["light"] = focus["light"]
    if "dark" in focus:
        updated["focus"]["dark"] = focus["dark"]
    if "ring" in focus:
        updated.setdefault("focus", {})["ring"] = focus["ring"]
    if found["icon_set"]:
        updated["icon_set"] = found["icon_set"]
    if found.get("button"):
        updated["button"] = found["button"]
    notes = enforce_contrast(updated)
    source = updated.setdefault("source", {})
    source["status"] = "extracted"
    source.pop("checkout", None)
    if git_ref:
        source["app_git_ref"] = git_ref
    source["icon_packages"] = found["icon_packages"]
    if found.get("icon_families"):
        source["icon_families"] = found["icon_families"]
    source["chakra_defaults"] = found.get("chakra_defaults", False)
    source["ui_packages"] = found["ui_packages"]
    source["detail"] = (
        "Values were read from frontend/ in the graph-ted checkout. "
        "Groups that were not named in that source are unchanged."
    )
    provenance = updated.setdefault("provenance", {})
    chakra = found.get("chakra_version") or "installed"
    if found.get("chakra_defaults"):
        source["chakra_version"] = found.get("chakra_version")
        base = (
            f"Chakra UI {chakra} defaultConfig, read from frontend/node_modules/@chakra-ui/react. "
            "The app theme extends defaultConfig and does not override this group."
        )
        if found["radius"]:
            provenance["radius"] = (
                base + " Buttons and inputs use l2 (the app's 4px control radius); "
                "code blocks and admonitions use md, the radius app panels set."
            )
        if found["spacing"]:
            provenance["spacing"] = base + " Exposed as --gt-space-* variables."
        if found.get("button"):
            provenance["button"] = (
                f"Chakra UI {chakra} button recipe, default size {found['button'].get('size')}: "
                "h, px, and textStyle resolved through the spacing, text-style, and font-size tokens."
            )
    if found["layout"].get("root_font_size"):
        provenance["layout.root_font_size"] = (
            "App globalCss html fontSize. Material's root is 125%, so app rem lengths "
            "are written to the stylesheet in px at this size."
        )
        if found["shadow"]:
            provenance["shadow"] = (
                base + " Semantic shadows, light and dark, with color references resolved "
                "the way Chakra emits them (color-mix)."
            )
    if found["font"].get("text"):
        provenance["font.text"] = (
            "App fonts.body token, copied as written. Inter is self-hosted here; "
            '"Inter Variable" is the app\'s @fontsource-variable family name and falls through to it.'
        )
    if found["icon_set"]:
        families = ", ".join(found.get("icon_families") or [])
        provenance["icon_set"] = (
            f"frontend/package.json depends on {', '.join(found['icon_packages'])}"
            + (f" (imported families, most used first: {families})" if families else "")
            + ". No SVGs are vendored, so Material's built-in icons stay in the docs."
        )
    # The checkout path is never written: it can name a local home directory.
    provenance["sync"] = "scripts/sync_tokens.py --from <graph-ted checkout>"
    if notes:
        provenance["contrast"] = " ".join(notes)
    return updated


def find_frontend(checkout: Path) -> Path:
    direct = checkout / "frontend"
    if (direct / "package.json").is_file():
        return direct
    if (checkout / "package.json").is_file():
        return checkout
    raise FileNotFoundError(
        f"no frontend/package.json under {checkout}. "
        "Pass a graph-ted checkout. Refusing to invent tokens."
    )


def write_outputs(tokens: dict, tokens_path: Path, css_path: Path, *, write_tokens: bool) -> None:
    css_path.parent.mkdir(parents=True, exist_ok=True)
    css_path.write_text(render_css(tokens), encoding="utf-8")
    if write_tokens:
        tokens_path.write_text(dump_tokens(tokens), encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 when extra.css does not match tokens.json",
    )
    parser.add_argument(
        "--from",
        dest="checkout",
        help="read-only graph-ted checkout (contains frontend/)",
    )
    parser.add_argument("--dry-run", action="store_true", help="with --from, print mappings only")
    parser.add_argument("--tokens", type=Path, default=DEFAULT_TOKENS)
    parser.add_argument("--css", type=Path, default=DEFAULT_CSS)
    args = parser.parse_args(argv)

    if args.check and args.checkout:
        print("pass either --check or --from, not both", file=sys.stderr)
        return 2

    tokens_path = args.tokens if args.tokens.is_absolute() else ROOT / args.tokens
    css_path = args.css if args.css.is_absolute() else ROOT / args.css
    if not tokens_path.is_file():
        print(f"missing tokens file: {tokens_path}", file=sys.stderr)
        return 2
    tokens = load_tokens(tokens_path)

    if args.checkout:
        checkout = Path(args.checkout)
        if not checkout.is_absolute():
            checkout = Path.cwd() / checkout
        try:
            frontend = find_frontend(checkout)
            found = extract_mappings(frontend)
        except FileNotFoundError as exc:
            print(str(exc), file=sys.stderr)
            return 2
        except json.JSONDecodeError as exc:
            print(f"could not parse frontend/package.json: {exc}", file=sys.stderr)
            return 2
        if not found["mapped"]:
            print(
                "frontend/package.json was readable, but no design tokens were named "
                "in theme or token files. Refusing to invent radii, spacing, shadows, "
                "colors, or an icon set.",
                file=sys.stderr,
            )
            return 2
        updated = apply_extraction(tokens, found, _app_git_ref(checkout))
        if args.dry_run:
            print(dump_tokens(updated))
            return 0
        write_outputs(updated, tokens_path, css_path, write_tokens=True)
        print(f"wrote {tokens_path}")
        print(f"wrote {css_path}")
        return 0

    rendered = render_css(tokens)
    if args.check:
        current = css_path.read_text(encoding="utf-8") if css_path.is_file() else ""
        if current != rendered:
            print(
                f"{css_path} is stale. Run: python scripts/sync_tokens.py",
                file=sys.stderr,
            )
            return 1
        print(f"{css_path} matches {tokens_path}")
        return 0

    css_path.write_text(rendered, encoding="utf-8")
    print(f"wrote {css_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
